import {FormEvent,useState} from 'react';import {LoaderCircle,CheckCircle2} from 'lucide-react';import {submitForm} from '../../services/forms';
type FormKind='enquiry'|'contact'|'visit'|'compact';type Props={kind?:FormKind;source:string;dark?:boolean};
const programmes=['Preschool','Primary School','After-School Programme','Weekend Programme','Coding & Robotics','School Visit','General Enquiry'];
export function SmartForm({kind='enquiry',source,dark=false}:Props){const [status,setStatus]=useState<'idle'|'loading'|'success'|'error'>('idle');const [errors,setErrors]=useState<Record<string,string>>({});async function send(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);if(form.get('website'))return;const required=kind==='visit'?['name','phone','date']:['name','email','phone'];const next:Record<string,string>={};required.forEach(k=>{if(!String(form.get(k)||'').trim())next[k]='This field is required.'});const email=String(form.get('email')||'');if(email&&!/^\S+@\S+\.\S+$/.test(email))next.email='Enter a valid email address.';const phone=String(form.get('phone')||'').replace(/\D/g,'');if(phone&&phone.length<10)next.phone='Enter a valid phone number.';if(Object.keys(next).length){setErrors(next);return}setErrors({});setStatus('loading');try{await submitForm(Object.fromEntries(form) as Record<string,string> & {type:string;source:string});setStatus('success');e.currentTarget.reset()}catch{setStatus('error')}}
if(status==='success')return <div role="status" className="rounded-2xl bg-green/10 p-6 text-green"><CheckCircle2 className="mb-3"/><strong>Thank you. Your enquiry has been received.</strong><p className="mt-2 text-sm">Our team will be in touch shortly.</p><button className="mt-4 underline" onClick={()=>setStatus('idle')}>Send another</button></div>;
const inputClass=`input ${dark?'border-white/20 bg-white/10 text-white placeholder:text-white/45':''}`;const field=(name:string,label:string,type='text')=><label><span className={`label ${dark?'text-white/80':''}`}>{label}</span><input className={inputClass} name={name} type={type} aria-invalid={!!errors[name]} aria-describedby={`${name}-error`}/>{errors[name]&&<span id={`${name}-error`} className="error">{errors[name]}</span>}</label>;
return <form onSubmit={send} noValidate className="grid gap-4 sm:grid-cols-2"><input className="hidden" name="website" tabIndex={-1} autoComplete="off"/><input type="hidden" name="type" value={kind==='visit'?'school-visit':kind==='contact'?'contact-enquiry':'admission-enquiry'}/><input type="hidden" name="source" value={source}/>{field('name',kind==='enquiry'?'Parent / Guardian Full Name *':'Full Name *')}{kind!=='visit'&&field('email','Email Address *','email')}{field('phone','Phone Number *','tel')}
{kind==='visit'?<>{field('date','Preferred Visit Date *','date')}<label><span className="label">Preferred Time</span><input className={inputClass} name="time" type="time"/></label>{field('visitors','Number of Visitors','number')}{field('childClass','Child Age / Class')}</>:<label><span className={`label ${dark?'text-white/80':''}`}>{kind==='contact'?'Subject':'Programme of Interest'}</span><select className={inputClass} name="programme">{programmes.map(x=><option className="text-slate-900" key={x}>{x}</option>)}</select></label>}
{kind==='enquiry'&&kind!=='compact'&&<>{field('childName',"Child's Name")}{field('childAge',"Child's Age")}{field('grade','Current Class / Grade')}<fieldset><legend className="label">Preferred Contact</legend><div className="flex gap-4 text-sm">{['Phone','WhatsApp','Email'].map(x=><label key={x}><input type="radio" name="contactMethod" value={x} defaultChecked={x==='WhatsApp'}/> {x}</label>)}</div></fieldset></>}
<label className="sm:col-span-2"><span className={`label ${dark?'text-white/80':''}`}>{kind==='visit'?'Notes':'Message / Additional Information'}</span><textarea className={inputClass} rows={kind==='compact'?2:4} name="message" maxLength={1000}/></label>{kind==='enquiry'&&kind!=='compact'&&<label className="flex items-start gap-3 text-sm sm:col-span-2"><input required className="mt-1 accent-green" type="checkbox" name="consent" value="yes"/> I agree to be contacted regarding my enquiry.</label>}{status==='error'&&<p role="alert" className="text-sm text-red-500 sm:col-span-2">We couldn't send this form. Please call or WhatsApp us.</p>}<button disabled={status==='loading'} className="min-h-12 rounded-full bg-gold px-6 font-bold text-navy transition hover:bg-white disabled:opacity-60 sm:col-span-2">{status==='loading'?<span className="flex items-center justify-center gap-2"><LoaderCircle className="animate-spin"/>Sending…</span>:'Send Enquiry'}</button></form>}
export const EnquiryForm=(p:Omit<Props,'kind'>)=><SmartForm {...p} kind="enquiry"/>;export const ContactForm=(p:Omit<Props,'kind'>)=><SmartForm {...p} kind="contact"/>;export const SchoolVisitForm=(p:Omit<Props,'kind'>)=><SmartForm {...p} kind="visit"/>;
